var app=new Vue({
    el:"#nav-bar",
    data:{
        "items":[
            {
                "title":"Inicio",
                "url":"#start",
                "img":"home"
            },
            {
                "title":"Experiencia",
                "url":"#experience",
                "img":"work"
            },
            {
                "title":"Portafolio",
                "url":"#portfolio",
                "img":"portfolio"
            },
            {
                "title":"Educación",
                "url":"#education",
                "img":"education"
            },
            {
                "title":"Habilidades",
                "url":"#habilities",
                "img":"skills"
            },
            {
                "title":"Reconocimientos",
                "url":"#awards",
                "img":"awards"
            }
        ]
    }
});
