var app=new Vue({
    el:"#social-network",
    data:{
        "networks":[
            {
                "title":"edgar730a@gmail.com",
                "url":"",
                "img":"email"
            },
            {
                "title":"Github",
                "url":"https://github.com/EdgarPozas",
                "img":"github"
            },
            {
                "title":"LinkedIn",
                "url":"https://www.linkedin.com/in/EdgarPozas",
                "img":"linkedin"
            },
            {
                "title":"Platzi",
                "url":"https://platzi.com/p/EdgarPozas/",
                "img":"platzi"
            }
        ]
    }
});
